/**
 * AXIP Demo — Client Script
 *
 * Sends a prospect_research task to the network and displays the result.
 * This script IS the demo — its terminal output should be impressive.
 *
 * Flow:
 *   1. Connect to relay
 *   2. Discover prospect_research agents
 *   3. Send task request for a target company
 *   4. Accept the best bid
 *   5. Wait for results
 *   6. Verify and display the report
 *   7. Exit
 */

import { AXIPAgent } from '@axip/sdk';
import chalk from 'chalk';

const PREFIX = chalk.yellow('[CLIENT]');
const DIVIDER = chalk.gray('═'.repeat(60));

async function main() {
  console.log('');
  console.log(DIVIDER);
  console.log(chalk.yellow.bold('  Network ready. Sending prospect research task...'));
  console.log(DIVIDER);
  console.log('');

  const agent = new AXIPAgent({
    name: 'demo-client',
    capabilities: [], // Client has no skills — only requests
  });

  await agent.start();
  console.log(`${PREFIX}  ${chalk.green('✓')} Connected to relay`);

  // Wait for agents to be fully registered
  await new Promise(r => setTimeout(r, 1000));

  // Step 1: Discover prospect_research agents
  console.log(`${PREFIX}  ${chalk.bold('►')} Discovering prospect_research agents...`);
  const discovered = await agent.discover('prospect_research');
  const agents = discovered.payload.agents;

  if (!agents || agents.length === 0) {
    console.log(chalk.red(`${PREFIX}  No prospect_research agents found. Exiting.`));
    agent.stop();
    process.exit(1);
  }

  console.log(`${PREFIX}  ${chalk.green('✓')} Found ${agents.length} agent(s)`);
  const target = agents[0];
  console.log(`${PREFIX}  ${chalk.gray('Best match:')} ${target.agent_id} (reputation: ${target.reputation})`);

  // Step 2: Send task request
  const TARGET = process.env.DEMO_TARGET || 'Salesforce recent news AI strategy funding';
  const TARGET_SHORT = TARGET.split(' ')[0];
  console.log('');
  console.log(`${PREFIX}  ${chalk.bold('►')} Requesting: prospect_research for ${chalk.white.bold(`"${TARGET_SHORT}"`)}`);
  console.log('');

  const taskMsg = agent.send('task_request', 'relay', {
    task_id: `task_demo_${Date.now()}`,
    description: TARGET,
    capability_required: 'prospect_research',
    constraints: { max_cost_usd: 0.20 },
    reward: 0.10
  });

  // Step 3: Handle bid
  agent.on('task_bid', async (msg) => {
    console.log(`${PREFIX}  ${chalk.bold('◄')} Bid received: $${msg.payload.price_usd} from ${msg.from.agent_id} (ETA: ${msg.payload.estimated_time_seconds}s)`);
    console.log(`${PREFIX}  ${chalk.green('✓')} Accepting bid...`);
    agent.acceptBid(msg.from.agent_id, msg.payload.task_id, msg.payload.bid_id);
  });

  // Step 4: Handle final result
  agent.on('task_result', async (msg) => {
    const report = msg.payload.output;

    console.log('');
    console.log(DIVIDER);
    console.log(chalk.green.bold('  RESULT: Prospect Research Report'));
    console.log(DIVIDER);
    console.log('');

    // Display the report beautifully
    console.log(chalk.white.bold(`  PROSPECT RESEARCH REPORT: ${report.company || 'Unknown'}`));
    console.log(chalk.gray(`  Generated by ${report.generated_by} via AXIP Network`));
    console.log(chalk.gray(`  Date: ${report.generated_at}`));
    console.log('');

    // Sources
    if (report.sources && report.sources.length > 0) {
      console.log(chalk.white.bold('  SOURCES (via AXIP web_search delegation):'));
      for (const source of report.sources) {
        console.log(chalk.cyan(`  ${chalk.bold('●')} ${source.title}`));
        console.log(chalk.gray(`    ${source.url}`));
        console.log(chalk.gray(`    ${source.summary?.slice(0, 100)}...`));
        console.log('');
      }
    }

    // Synthesis
    if (report.synthesis) {
      console.log(chalk.white.bold('  SYNTHESIS:'));
      console.log(chalk.white(`  ${report.synthesis.summary}`));
      console.log('');

      if (report.synthesis.key_findings?.length > 0) {
        console.log(chalk.white.bold('  KEY FINDINGS:'));
        for (const finding of report.synthesis.key_findings) {
          console.log(chalk.white(`  • ${finding}`));
        }
        console.log('');
      }

      console.log(chalk.white.bold('  OUTREACH ANGLE:'));
      console.log(chalk.white(`  ${report.synthesis.outreach_angle}`));
      console.log('');
    }

    // AXIP metadata
    if (report.axip_metadata) {
      console.log(chalk.gray.bold('  AXIP TASK METADATA:'));
      console.log(chalk.gray(`  • Search delegated to: ${report.axip_metadata.search_delegated_to}`));
      console.log(chalk.gray(`  • Search cost: $${report.axip_metadata.search_cost_usd}`));
      console.log(chalk.gray(`  • Search time: ${report.axip_metadata.search_time_seconds}s`));
      console.log(chalk.gray(`  • Total task cost: $${report.axip_metadata.total_task_cost_usd}`));
      console.log('');
    }

    // Verify the result
    console.log(`${PREFIX}  ${chalk.bold('►')} Verifying result (quality: 0.90)...`);
    agent.verifyResult(msg.from.agent_id, msg.payload.task_id, true, 0.90, 'Excellent research report');

    // Wait for settlement
    await new Promise(r => setTimeout(r, 2000));

    console.log(`${PREFIX}  ${chalk.green.bold('✓ Task complete. Settlement processed.')}`);
    console.log('');

    // Clean exit
    agent.stop();
    setTimeout(() => process.exit(0), 500);
  });

  // Timeout if no result after 120 seconds (Ollama LLM summarization can take a while)
  setTimeout(() => {
    console.error(chalk.red(`${PREFIX} Timeout: No result received after 120 seconds`));
    agent.stop();
    process.exit(1);
  }, 120_000);
}

main().catch(err => {
  console.error(chalk.red(`[CLIENT] FATAL: ${err.message}`));
  process.exit(1);
});
